export {default as GetStarted} from './GetStarted'
export {default as Home} from './Home'
export {default as Recipes} from './MyRecipes'
export {default as MyList} from './GroceryList'
export {default as Search} from './Search'